//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Managment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class create_books
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public create_books()
        {
            this.crud_book = new HashSet<crud_book>();
        }
    
        public int book_id { get; set; }
        public string book_name { get; set; }
        public string book_description { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<int> book_user_id { get; set; }
    
        public virtual user_tbl user_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<crud_book> crud_book { get; set; }
    }
}
