//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Managment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class crud_book
    {
        public int issue_id { get; set; }
        public System.DateTime issue_from { get; set; }
        public System.DateTime issue_to { get; set; }
        public string person_name { get; set; }
        public string book_name { get; set; }
        public Nullable<int> cr_id { get; set; }
    
        public virtual create_books create_books { get; set; }
    }
}
